plugins {
    id 'org.springframework.boot'
}

description = 'Inventory service for checkout tracing demo'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.nextbi.dataflow:tracing-common:0.0.2'
    implementation 'io.opentracing:opentracing-api:0.33.0'
    implementation 'io.opentracing:opentracing-util:0.33.0'
    implementation 'io.jaegertracing:jaeger-client:1.3.2'
    implementation 'org.apache.thrift:libthrift:0.13.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
