spring.application.name=api-gateway
server.port=8080

client.order-service.base-url=http://localhost:8081
client.inventory-service.base-url=http://localhost:8082
client.pricing-service.base-url=http://localhost:8083
client.payment-service.base-url=http://localhost:8084

management.endpoints.web.exposure.include=health,info,beans,metrics,prometheus
management.endpoint.health.probes.enabled=true
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.client.requests=true
management.metrics.distribution.slo.http.server.requests=100ms,250ms,500ms,1s,2s,5s
spring.boot.admin.client.url=http://localhost:9090
spring.boot.admin.client.instance.service-base-url=http://localhost:${server.port}
spring.boot.admin.client.instance.management-base-url=http://localhost:${server.port}

opentracing.jaeger.enabled=true
opentracing.jaeger.service-name=${spring.application.name}
opentracing.jaeger.http-sender.url=http://localhost:14268/api/traces
opentracing.jaeger.log-spans=false
opentracing.jaeger.const-sampler.decision=true
