spring.application.name=api-gateway
server.port=8080

client.order-service.base-url=http://localhost:8081

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
