services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.3.6
    container_name: sample-for-tracing-redpanda
    restart: unless-stopped
    command:
      - redpanda
      - start
      - --mode
      - dev-container
      - --smp
      - "1"
      - --memory
      - 512M
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - internal://0.0.0.0:29092,external://0.0.0.0:9092
      - --advertise-kafka-addr
      - internal://redpanda:29092,external://localhost:9092
    ports:
      - "9092:9092"

  jaeger:
    build:
      context: ./jaeger
    container_name: sample-for-tracing-jaeger
    restart: unless-stopped
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
