FROM jaegertracing/all-in-one:1.67.0

LABEL org.opencontainers.image.title="sample-for-tracing-jaeger"
LABEL org.opencontainers.image.description="Local Jaeger all-in-one image for SampleForTracing"

EXPOSE 16686 14268 14250 4317 4318 9411 5778 6831/udp 6832/udp
